Acceptance tests
maler306/sof pull request #3
Opened 2017-11-17 08:23 UTC by maler306

2017-11-17 14:04 UTC, vkurennov requested changes

2017-11-17 14:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_back fallback_location: @question
Нельзя делать редирект, если есть ошибки валидации. Нужно делать рендер страницы, иначе все что ввел пользователь, как и результаты валидации будут утеряны.

2017-11-17 14:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Your are not author of the answer'
Если сообщение должно быть на той же странице, без редиректа, то надо устанавливать его через `flash.now[:notice]`

2017-11-17 14:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Your are not author of the answer'
И в этом случае, у тебя будет попытка рендерить вид destroy.html., а этого не нужно. Лучше в явном виде указать какую страницу отрендерить (или сделать редирект в обоих случаях)

2017-11-17 14:04 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User as author can delete own answer' , js: true do
Нужен сценарий, когда гость и не-автор не видят ссылки на удаление

2017-11-17 14:04 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить заголовок и тело вопроса на странице

2017-11-17 14:04 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на невалидный вопрос - проверить, что система выводит ошибки валидации

2017-11-17 14:04 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен сценарий на невалидный ответ - проверить, что система выводит ошибки валидации

2017-11-17 14:04 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Тут надо еще и связь с юзером проверить

2017-11-17 14:04 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'not deletes answer' do
А какой рендер/редирект в этом случае должен быть?

2017-11-17 14:04 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Нужно проверить связь с юзером.

2017-11-17 14:04 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
А где тесты на метод `owner?`

2017-11-22 13:34 UTC, maler306 commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Your are not author of the answer'
Так и не смог сделать отображение ошибок при рендеринге на ту же страницу через flash.now[:notice]. Пробовал на экшенах create и update, но без успешно. Подсмотрел у коллег, как они сделали с использованием JS только тогда ошибки стали отображаться.

2017-11-23 08:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'Your are not author of the answer'
Ну js тут еще рано было применять. А вообще, для destroy вполне можно было использовать редирект и обычный flash

2017-11-23 08:11 UTC, vkurennov requested changes

2017-11-23 08:11 UTC, vkurennov commented on app/assets/javascripts/application.js
> +//= require jquery_ujs
Надо оставить либо jquery_ujs либо rails-ujs, но не оба, иначе, они будут конфликтовать. В курсе используется jquery_ujs, поэтому рекомендую оставить его.

2017-11-23 08:11 UTC, vkurennov commented on app/views/answers/create.js.erb
> +$('.flash').html('<%= flash[:notice] %>');
Хм, ты забежал вперед и сделал следующее задание сразу :-) Пока надо было все сделать без ajax, ну ладно, не переделывать же теперь.

2017-11-23 08:11 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User as author can delete own answer' , js: true do
Не исправлено, где эти 2 сценария?

2017-11-23 08:11 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +    sign_in(other_user)
У тебя в сценарии написано  "Non-authenticated user", а тут ты его логинишь. Нужно 2 разных сценария сделать: юзер не залогинен вообще и юзер залогинен, но не является автором

2017-11-23 08:11 UTC, vkurennov commented on spec/acceptance/questions/show_question_spec.rb
> +    "#{answers.each {|answer| expect(page).to have_content answer.body } }"
А зачем тут интерполяция-то?! Давай весь код тогда в строках с интерполяцией писать, так что ли?

2017-11-23 08:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Не исправлено.

2017-11-23 08:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer:  attributes_for(:invalid_answer), format: :js  } }.to_not change(question.answers, :count)
тут в change должен быть просто Answer, т.к. важно проверить, что ответ в принципе не был сохранен, вне зависимости от его связей.

2017-11-23 08:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'not deletes answer' do
Не исправлено

2017-11-23 08:55 UTC, maler306 commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User as author can delete own answer' , js: true do
scenario 'User do not see links for editing or delete not his answer' в edit_answer_spec.rb

2017-11-23 08:58 UTC, maler306 commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Не понял, ниже ведь есть expect(page).to have_content 'Test question'

2017-11-23 10:24 UTC, maler306 commented on spec/acceptance/answers/create_answer_spec.rb
> +feature 'Create answer', %q{
сценарий ниже на строке 24
expect(page).to have_content 'Body is too short (minimum is 10 characters)'
разве не то, что нужно?

2017-11-23 10:29 UTC, maler306 commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User as author can delete own answer' , js: true do
scenario 'Non-authenticated user  do not see links for editing or delete not his answer'
там же, я подумал какой смысл писать один и тот же код в разных местах. В скринкасте говорилось о том, что нужно мыслить категориями страниц, элементов страниц и видимого пользователю функционала абстрагируясь от моделей и контроллеров. Или я не так понял?

2017-11-23 10:31 UTC, maler306 commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
26 строка
 scenario 'Authenticated user try to create the question with invalid data' do

    sign_in(user)

    visit '/questions'
    click_on 'Ask question'
    fill_in 'Title', with: 'Te'
    fill_in 'Text', with: 'te'
    click_on 'Create'

    expect(page).to have_content 'Title is too short (minimum is 5 characters)'
    expect(page).to have_content 'Body is too short (minimum is 5 characters)'
    expect(page).to have_field('Title', :with => 'Te')
    expect(page).to have_field('Text', :with => 'te')
  end

2017-11-24 08:53 UTC, vkurennov approved these changes

2017-11-24 08:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      if @answer.save
А почему тут отступ?

2017-11-24 08:53 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +feature 'Create answer', %q{
Ну так этот комментарий остался с прошлой проверки просто.

2017-11-24 08:53 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User as author can delete own answer' , js: true do
А почему они в  edit_answer_spec.rb? У тебя фича называется "Delete answer", в ней и должны быть все сценарии, связанные с удалением. А в  edit_answer_spec.rb только то, что связано с редактированием. Нужно же логически код группировать. А то как догадаться, куда ты какой-либо сценарий закинул? Представь что ты приходишь на проект и хочешь посмотреть тесты, открываешь фичу по удалению видишь один сценарий, где остальные? искать перебором по всем файлам?

2017-11-24 08:53 UTC, vkurennov commented on spec/acceptance/answers/edit_answer_spec.rb
> +    expect(page).to_not have_button 'Delete answer'
Это не относится к удалению, а не к редактированию. И должен быть в соотвсетвующей фиче

2017-11-24 08:53 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'Create question', %q{
это старое замечание, с предыдущей проверки

2017-11-24 08:53 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
И опять же это старый комментарий, не с последней проверки, а до нее

2017-11-24 11:19 UTC, merged